// Generates every app icon from one definition.
//
// Run with: node scripts/generate-icons.mjs
//
// The SVGs in public/ are OUTPUTS of this script, not sources — editing them
// by hand puts them out of step with the PNGs, and the PNGs are what iOS and
// Android actually use. Change the artwork here and re-run.
//
// Three shapes come out of the same drawing, because the platforms want
// different things:
//
//   rounded    — icon.svg, icon-192.png, icon-512.png. Shown as-is by browsers
//                and by the PWA install prompt, so it carries its own corner
//                radius.
//   square     — apple-touch-icon.png. iOS applies its own squircle mask, so
//                this must be full-bleed with NO rounding of its own; a
//                pre-rounded source gets masked twice and shows dark corners.
//   maskable   — icon-maskable-512.png. Android crops to whatever shape the
//                launcher uses, so the artwork sits inside the middle 80% and
//                only the background runs to the edge.

import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import sharp from "sharp";

const PUBLIC = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "public",
);

// --primary from globals.css. Written literally because an icon is fetched by
// the operating system, which has no stylesheet to resolve a token against.
const BLUE = "#0071c2";
const WHITE = "#ffffff";

// The same mark the header uses: lucide's `plane`, on a 24x24 grid.
const PLANE =
  "M17.8 19.2 16 11l3.5-3.5C21 6 21.5 4 21 3c-1-.5-3 0-4.5 1.5L13 8 4.8 6.2c-.5-.1-.9.1-1.1.5l-.3.5c-.2.5-.1 1 .3 1.3L9 12l-2 3H4l-1 1 3 2 2 3 1-1v-3l3-2 3.5 5.3c.3.4.8.5 1.3.3l.5-.2c.4-.3.6-.7.5-1.2z";

// The drawing, without a background. Kept separate so the maskable variant can
// scale it into the safe zone without touching the background.
//
// No wordmark, deliberately. An earlier version set "MyTrip" under the plane;
// at the size this is actually seen — roughly 60px on a home screen — the
// letters smear, and iOS already prints the app's name directly beneath the
// icon. The name was appearing twice and one of the two was unreadable. The
// mark alone is what survives at that size, so it is the whole icon.
//
// The plane sits slightly above centre and the route arc below it, which
// leaves the optical weight balanced now that nothing follows underneath.
// The two elements are sized so the plane's tail clears the arc's apex rather
// than crossing it. With the wordmark gone there is room to separate them, and
// dots running through the tail's outline read as noise at small sizes — the
// one place this icon has to work hardest.
const artwork = `
    <path d="M96 392 C 172 320, 340 320, 416 392"
          fill="none" stroke="${WHITE}" stroke-width="15"
          stroke-linecap="round" stroke-dasharray="3 36" opacity="0.8" />
    <g transform="translate(256 222) scale(12) translate(-12 -12)">
      <path d="${PLANE}" fill="none" stroke="${WHITE}" stroke-width="2"
            stroke-linecap="round" stroke-linejoin="round" />
    </g>`;

function svg({ rounded = false, inset = 1 } = {}) {
  const corner = rounded ? ' rx="112"' : "";
  const scaled =
    inset === 1
      ? artwork
      : `<g transform="translate(256 256) scale(${inset}) translate(-256 -256)">${artwork}</g>`;

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" role="img" aria-label="MyTrip">
  <!-- Generated by scripts/generate-icons.mjs. Do not edit by hand. -->
  <rect width="512" height="512"${corner} fill="${BLUE}" />${scaled}
</svg>
`;
}

const rounded = svg({ rounded: true });
const square = svg({ rounded: false });
// 0.8 is the maskable safe zone: Android may crop anything outside the middle
// 80% of the canvas.
const maskable = svg({ rounded: false, inset: 0.8 });

async function png(source, size, name) {
  await sharp(Buffer.from(source), { density: 512 })
    .resize(size, size)
    .png()
    .toFile(path.join(PUBLIC, name));
  console.log(`  ${name} (${size}x${size})`);
}

console.log("writing SVGs");
await writeFile(path.join(PUBLIC, "icon.svg"), rounded, "utf8");
await writeFile(path.join(PUBLIC, "icon-maskable.svg"), maskable, "utf8");
console.log("  icon.svg, icon-maskable.svg");

console.log("rasterising PNGs");
await png(rounded, 192, "icon-192.png");
await png(rounded, 512, "icon-512.png");
await png(maskable, 512, "icon-maskable-512.png");
// Full-bleed square: iOS rounds it itself.
await png(square, 180, "apple-touch-icon.png");

console.log("done");
