// Generates every app icon from one definition.
//
// Run with: node scripts/generate-icons.mjs
//
// The SVGs in public/ are OUTPUTS of this script, not sources — editing them
// by hand puts them out of step with the PNGs, and the PNGs are what iOS and
// Android actually use. Change the artwork here and re-run.
//
// Three shapes come out of the same drawing, because the platforms want
// different things:
//
//   rounded    — icon.svg, icon-192.png, icon-512.png. Shown as-is by browsers
//                and by the PWA install prompt, so it carries its own corner
//                radius.
//   square     — apple-touch-icon.png. iOS applies its own squircle mask, so
//                this must be full-bleed with NO rounding of its own; a
//                pre-rounded source gets masked twice and shows dark corners.
//   maskable   — icon-maskable-512.png. Android crops to whatever shape the
//                launcher uses, so the artwork sits inside the middle 80% and
//                only the background runs to the edge.

import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import sharp from "sharp";

const PUBLIC = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "public",
);

// --primary from globals.css. Written literally because an icon is fetched by
// the operating system, which has no stylesheet to resolve a token against.
const BLUE = "#0071c2";
const WHITE = "#ffffff";

// The same mark the header uses: lucide's `plane`, on a 24x24 grid.
const PLANE =
  "M17.8 19.2 16 11l3.5-3.5C21 6 21.5 4 21 3c-1-.5-3 0-4.5 1.5L13 8 4.8 6.2c-.5-.1-.9.1-1.1.5l-.3.5c-.2.5-.1 1 .3 1.3L9 12l-2 3H4l-1 1 3 2 2 3 1-1v-3l3-2 3.5 5.3c.3.4.8.5 1.3.3l.5-.2c.4-.3.6-.7.5-1.2z";

// The drawing, without a background. Kept separate so the maskable variant can
// scale it into the safe zone without touching the background.
//
// The wordmark is a <path>, not a <text> element, on purpose: librsvg (what
// sharp rasterises with) resolves fonts through fontconfig, and on a machine
// where the named family is missing it silently substitutes or drops the text
// altogether. A logo that depends on the build machine's installed fonts is a
// logo that renders differently on CI. Outlines have no such dependency.
const artwork = `
    <path d="M112 330 C 180 272, 332 272, 400 330"
          fill="none" stroke="${WHITE}" stroke-width="13"
          stroke-linecap="round" stroke-dasharray="3 32" opacity="0.8" />
    <g transform="translate(256 196) scale(10.4) translate(-12 -12)">
      <path d="${PLANE}" fill="none" stroke="${WHITE}" stroke-width="2"
            stroke-linecap="round" stroke-linejoin="round" />
    </g>
    <g transform="translate(256 428)">
      ${wordmark()}
    </g>`;

// "MyTrip" as outlines, drawn on a 100-unit cap height and centred on (0,0).
// Geometric sans forms, matched to the header's weight rather than to a
// specific typeface — at icon size the letterforms read as a shape, not as
// type, and a webfont would be a dependency for six glyphs.
function wordmark() {
  // Each glyph is authored on a baseline of 0, growing upward, then the whole
  // run is shifted so its optical centre sits at the origin.
  const glyphs = [
    // M
    "M0 0 v-96 h20 l24 58 24-58 h20 v96 h-19 v-62 l-19 46 h-12 l-19-46 v62 z",
    // y
    "M96 26 q10 3 16-1 5-3 8-12 l3-8 -29-71 h20 l18 48 17-48 h20 l-32 82 q-7 18-17 24 -9 5-24 2 z",
    // T
    "M170 0 v-79 h-28 v-17 h75 v17 h-28 v79 z",
    // r
    "M228 0 v-70 h18 v11 q6-13 22-12 v18 q-22-3-22 18 v35 z",
    // i
    "M283 0 v-70 h19 v70 z M283-82 v-19 h19 v19 z",
    // p
    "M317 26 v-96 h18 v9 q7-11 21-11 22 0 30 20 4 9 4 18 0 22-13 31 -7 5-18 5 -14 0-23-10 v34 z M335-35 q0 12 7 18 5 4 12 4 18 0 18-22 0-22-18-22 -7 0-12 4 -7 6-7 18 z",
  ];

  // Measured from the outlines above: the run spans 0..390 horizontally and
  // sits between -101 and +26 vertically. Centring on the cap height rather
  // than the full extent keeps the descender of "y" and "p" from pushing the
  // word visually high.
  const width = 390;
  const capCentre = -48;
  const scale = 0.86;

  return `<g transform="scale(${scale}) translate(${-width / 2} ${-capCentre})">
        <path d="${glyphs.join(" ")}" fill="${WHITE}" fill-rule="evenodd" />
      </g>`;
}

function svg({ rounded = false, inset = 1 } = {}) {
  const corner = rounded ? ' rx="112"' : "";
  const scaled =
    inset === 1
      ? artwork
      : `<g transform="translate(256 256) scale(${inset}) translate(-256 -256)">${artwork}</g>`;

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" role="img" aria-label="MyTrip">
  <!-- Generated by scripts/generate-icons.mjs. Do not edit by hand. -->
  <rect width="512" height="512"${corner} fill="${BLUE}" />${scaled}
</svg>
`;
}

const rounded = svg({ rounded: true });
const square = svg({ rounded: false });
// 0.8 is the maskable safe zone: Android may crop anything outside the middle
// 80% of the canvas.
const maskable = svg({ rounded: false, inset: 0.8 });

async function png(source, size, name) {
  await sharp(Buffer.from(source), { density: 512 })
    .resize(size, size)
    .png()
    .toFile(path.join(PUBLIC, name));
  console.log(`  ${name} (${size}x${size})`);
}

console.log("writing SVGs");
await writeFile(path.join(PUBLIC, "icon.svg"), rounded, "utf8");
await writeFile(path.join(PUBLIC, "icon-maskable.svg"), maskable, "utf8");
console.log("  icon.svg, icon-maskable.svg");

console.log("rasterising PNGs");
await png(rounded, 192, "icon-192.png");
await png(rounded, 512, "icon-512.png");
await png(maskable, 512, "icon-maskable-512.png");
// Full-bleed square: iOS rounds it itself.
await png(square, 180, "apple-touch-icon.png");

console.log("done");
